### PR TITLE
feat(plugins): Add easier-stringguess

### PR DESCRIPTION
**Pull request by a-random-lemurian**
As suggested in https://github.com/naev/naev/pull/2674

### CODE REVIEW

**Comment by bobbens** [comment]
Is the repository https://github.com/a-random-lemurian/easier-stringguess public? I can't open it.

**Comment by a-random-lemurian** [comment]
> Is the repository https://github.com/a-random-lemurian/easier-stringguess public? I can't open it.

Forgot to mark it public, oops. I always push new repos as private as a sort of double check before I make them public.

**Comment by a-random-lemurian** [comment]
And now it's public

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
